### PR TITLE
Add split, append, push, pop methods

### PR DESCRIPTION
**Pull request by fizyk20**
@novacrazy I'm creating this as a PR to get your feedback ;)

I've had a go at creating a generic `split` method, and reimplementing some of your ideas under different names. This doesn't yet use the inverse traits idea, but I've run out of time today and I don't know when I'll be able to try and complete it, so I've decided to push it in this shape.

I'm not sure if I haven't missed some memory safety problems in my implementations, but the tests seem to indicate that this works. Please take a look, maybe something along those lines would be an easier way of implementing the functionality you need.

Of course feedback from anyone else is also welcome :)

### CODE REVIEW

**Comment by novacrazy** [comment]
Thank you for not forgetting this. I promise I haven't either, and as soon as I get a break at work I'll get back to this stuff.

One thing that concerns me in your code is calling `mem::forget(self)` before dereferencing pointers into `self`, since those pointers would then be dangling. It would be better to put the results into a temporary variable and then forget `self`.

I was concerned about pointer alignment for the offset pointers, but the more I think about it the less it probably matters. After all, normal slices just use pointer offsets, so it should be good enough for us.

**Comment by fizyk20** [comment]
>Thank you for not forgetting this. I promise I haven't either, and as soon as I get a break at work I'll get back to this stuff.

No problem - understandable that work comes first :)

>One thing that concerns me in your code is calling `mem::forget(self)` before dereferencing pointers into `self`, since those pointers would then be dangling. It would be better to put the results into a temporary variable and then forget `self`.

Hmm... Are those pointers really dangling? I mean, `forget` just causes the destructors not to run, it doesn't free the memory or anything. It's not even marked as unsafe. I don't think it's a problem - but I'm not sure, to be honest.

>I was concerned about pointer alignment for the offset pointers, but the more I think about it the less it probably matters. After all, normal slices just use pointer offsets, so it should be good enough for us.

Yes, I also think it should be okay.

**Comment by novacrazy** [comment]
> Are those pointers really dangling?

Yes, because `mem::forget` moves and consumes the value. It probably doesn't free it from the stack immediately on such a small function, which is why it works in the tests, but referring to memory that is otherwise inaccessible according to the lifetime rules is undefined behavior. `mem::{forget, drop}` should always be the last interaction with any object.

**Comment by fizyk20** [comment]
Okay, it won't be a problem to change it. Thanks for the explanation!

**Comment by fizyk20** [comment]
Covered by #50

**Pull request closed without merging**
