### PR TITLE
Switch from the long forsaken Travis CI build to using GitHub Actions

### PR DESCRIPTION
**Pull request by alexschrod**
I was thinking that in the spirit of an upcoming 1.0 release, it'd be useful to have a proper CI setup back up and running. So that's what this PR provides!

You can [see a sample run of this action in my forked repo](https://github.com/alexschrod/generic-array/actions). In addition to providing CI (both for master branch and for PRs), this action also publishes docs to the repo's GH pages branch (only on pushes to the master branch), ensuring that the documentation link in the README doesn't keep getting more and more outdated. [Here's the latest copy of the docs as automatically generated and pushed to my fork](https://alexschrod.github.io/generic-array/) by this very GH Actions setup.

Setting this whole thing up even let me [discover a mistake](https://github.com/fizyk20/generic-array/commit/74f4ee180c847528cd28361234db53a73e131c5e) in the `impl_zeroize.rs` file that had gone unnoticed without CI.

In order for the documentation to be published successfully, the `GITHUB_TOKEN` must be given write permissions to the repo, otherwise it can't push to the `gh-pages` branch. The CI.yml file should be simple enough to vet to ensure that I'm not up to anything mischievous, since you otherwise have no obvious reason to trust me. Instructions on [how to enable this write permission](https://github.com/JamesIves/github-pages-deploy-action/issues/1110#issuecomment-1117481234). You'll want to change this setting before merging this PR if you want the documentation publish to succeed.

### CODE REVIEW

**Comment by novacrazy** [comment]
@fizyk20 will need to do this, as I don't have the ability to enable the write permission. Otherwise, looks good to me.

**Comment by novacrazy** [comment]
I think the only build/test step should be `cargo miri test --all-features`, which will build and test with miri in a single step. Save as much time as we can, since miri acts as a separate build target anyway and requires recompilation.

**Comment by alexschrod** [comment]
Alright. In my own projects I would want to run my code on both real hardware and in the Miri interpreted, out of an abundance of caution, but 10-4. 😄

**Comment by fizyk20** [comment]
As far as I can tell, the relevant setting is already set correctly, so I'm merging this PR. Thank you!

**Pull request merged**
